### ISSUE TITLE
Survey Responses Not Sending Correct Data

### ISSUE THREAD

**Issue by ntelfer** [reputage/seedQuest#310] opened 2019-03-19 21:26 UTC
**Description**
In V5 prototype the survey data sent to the server is full of dummy data and the users actual responses are ignored.

**To Reproduce**
1. Download V5 of the prototype
2. Click the Survey button
3. Fill out the survey
4. Submit your response
5. Look at the survey data at http://178.128.0.208:8000/surveys?limit=1000

**Expected Behavior**
your responses show up

**Actual Behavior**
A new response shows up but it has dummy data and questions that weren't on the survey

**Device Info (please complete the following information):**
 - OS: Windows
 - Version V5

**Comment by westonb7** [comment] 2019-03-20 02:51
I can't reproduce this bug on my own machine running windows 10, it can successfully submit data that shows up on the server and uses the responses I entered instead of default ones - I'll make a separate survey debugging build to help figure this one out.

**Comment by ntelfer** [comment] 2019-03-20 15:23
After further investigation my filtering of responses was messing things up.  The data is coming through. There do seem to be questions in the data that aren't in the survey.  not sure if I'm looking at old data or not but @westonb7 I think you mentioned something about this.

**Comment by westonb7** [comment] 2019-03-20 15:45
Yes, the extra question issue should be resolved in the next demo. The extra questions in the post request are because those questions exist in the survey's question list (in the SurveyData scriptable object), but aren't getting displayed to the user. I've removed the extra questions from the list in an update in the 'survey-debugging' branch of the sandbox build.

**Closed** 2019-03-20 15:52 UTC
Labels: bug, p1
